version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - KEY_AUTH=${KEY_AUTH}
        - TOKEN_AUTH=${TOKEN_AUTH}
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
